version: '3.8'
services:
  web:
    image: api-gateway-local
    build: .
    command: start-local
    env_file: .env
    restart: unless-stopped
    ports:
      - 3000:${PORT}
    networks:
      standardnotes_proxy:
        aliases:
          - api_gateway
      api_gateway: {}
    volumes:
      - .:/var/www

  cache:
    image: redis:6.0-alpine
    volumes:
      - ./data/redis/:/data
    expose:
      - 6379
    ports:
      - 6380:6379
    networks:
      - api_gateway

networks:
  api_gateway:
    name: api_gateway
  standardnotes_proxy:
    name: standardnotes
